feat: Add support for lsp semantic highlight
ellisonleao/gruvbox.nvim pull request #243
Opened 2023-04-14 06:44 UTC by cryptomilk

This adds support for lsp semantic highlight with neovim >= 0.9

2023-04-14 22:26 UTC, ellisonleao requested changes

2023-04-14 22:26 UTC, ellisonleao commented on lua/gruvbox/groups.lua
> +    ["@macro"] = { link = "Macro" },
nice

2023-04-14 22:26 UTC, ellisonleao commented on lua/gruvbox/init.lua
> +        vim.api.nvim_set_hl(0, "@lsp.type.class", { link = "@constructor" })
can you move this to the groups list, please? I don't want that extra check there for nvim version. It will make it impossible to override if needed.

2023-04-15 06:33 UTC, cryptomilk commented on lua/gruvbox/init.lua
> +        vim.api.nvim_set_hl(0, "@lsp.type.class", { link = "@constructor" })
I've moved it, we can also just match the pattern to the colorscheme name.

2023-04-15 20:26 UTC, ellisonleao commented on lua/gruvbox/init.lua
> +        vim.api.nvim_set_hl(0, "@lsp.type.class", { link = "@constructor" })
hey @cryptomilk sorry if i wasn't clear, i've asked you to just move the color groups to the main groups list and remove the version check and the autocmd creation. Is it clear?

2023-04-16 06:10 UTC, cryptomilk commented
Oh sorry, I also misunderstood something form the docs. Fixed ...

2023-04-16 14:48 UTC, ellisonleao commented on lua/gruvbox/groups.lua
> -    -- semantic token
Are those replaced by the @lsp ones?

2023-04-17 06:49 UTC, cryptomilk commented on lua/gruvbox/groups.lua
> -    -- semantic token
Those are not replaced. They were never defined upstream. They were probably for an attempt to add semantic tokens which never made it upstream.

2023-04-17 14:53 UTC, merged

2023-05-19 20:46 UTC, timsofteng commented
It looks pretty strange in .tsx files. The highlighting without semantic tokens looksore colorful than with them. @cryptomilk may you take a look at this please? Is it ok?