fix(groups): Improve special comment keywords
ellisonleao/gruvbox.nvim pull request #247
Opened 2023-04-19 12:14 UTC by cryptomilk

This improve special comment keywords.

Here is how it will look like:

![gruvbox-comments](https://user-images.githubusercontent.com/545480/233071476-f6889174-0f5f-4001-8925-8292dfe6abbf.png)

2023-04-22 15:32 UTC, ellisonleao requested changes

2023-04-22 15:32 UTC, ellisonleao commented on lua/gruvbox/groups.lua
> +    Todo = { fg = colors.bg0, bg = colors.yellow, italic = config.italic.comments },
can you keep the bold config please?

2023-04-22 15:32 UTC, ellisonleao commented on lua/gruvbox/groups.lua
> +    ["@text.note.comment"] = { fg = colors.purple },
can you add the bold config here too?

2023-04-22 15:32 UTC, ellisonleao commented on lua/gruvbox/groups.lua
> +    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red },
can you add the bold config here too?

2023-04-23 06:16 UTC, cryptomilk commented on lua/gruvbox/groups.lua
> +    Todo = { fg = colors.bg0, bg = colors.yellow, italic = config.italic.comments },
Done.

2023-04-23 13:28 UTC, merged

2023-05-04 18:32 UTC, willeccles commented
Is there a convenient way to undo this in my config? I can't find a clean way to have the equivalent of `fg = colors.fg0` in `overrides` and I do not like the new highlighting.